baseURL = "/"
title = "Kentik Labs"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["kentik-labs"]

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"

[[menu.main]]
  name = "Blog"
  url = "/blog/"
