baseURL = "/"
title = "Kentik Labs | Open-source Network Observability Projects"
description = "Kentik Labs is a community hub developed by the team at Kentik.com. At our core, we are the data-dreaming network nerds who built an observability platform that makes much of the internet go."

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["kentik-labs"]

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
  [[menu.main]]
    name = "About"
    url = "/about/"
  [[menu.main]]
    name = "Blog"
    url = "/blog"

